# Generated by Django 4.1.4 on 2023-02-18 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Good')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='Price')),
                ('published', models.DateField(auto_now_add=True, db_index=True, verbose_name='Published date')),
            ],
        ),
        migrations.DeleteModel(
            name='Bb',
        ),
    ]
