# Generated by Django 4.1.4 on 2023-02-18 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0002_goods_delete_bb'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='category',
            field=models.TextField(blank=True, verbose_name='Category'),
        ),
    ]
